name: Docker Image CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Save JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/*.jar

  docker_build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: jar
          path: docker/
      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag my-image:dev
      - name: Test Run the Docker image
        run: docker run my-image:dev
